/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./src/**/*.{ts,tsx}', './App.tsx'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        /* Material Design 3 — The Archivist color tokens */
        m3: {
          primary: '#745b00',
          'primary-container': '#ffcb05',
          'on-primary': '#ffffff',
          'on-primary-container': '#6f5700',
          'on-primary-fixed': '#241a00',
          'on-primary-fixed-variant': '#584400',
          'primary-fixed': '#ffe08d',
          'primary-fixed-dim': '#f2c000',
          'inverse-primary': '#f2c000',
          secondary: '#0061a5',
          'secondary-container': '#73b4ff',
          'on-secondary': '#ffffff',
          'on-secondary-container': '#004579',
          'secondary-fixed': '#d2e4ff',
          'secondary-fixed-dim': '#a0caff',
          'on-secondary-fixed': '#001c37',
          'on-secondary-fixed-variant': '#00497e',
          tertiary: '#c00008',
          'tertiary-container': '#ffc3bb',
          'on-tertiary': '#ffffff',
          'on-tertiary-container': '#b70007',
          'tertiary-fixed': '#ffdad5',
          'tertiary-fixed-dim': '#ffb4a9',
          'on-tertiary-fixed': '#410001',
          'on-tertiary-fixed-variant': '#930004',
          surface: '#f9f9fc',
          'surface-dim': '#dadadc',
          'surface-bright': '#f9f9fc',
          'surface-container': '#eeeef0',
          'surface-container-low': '#f3f3f6',
          'surface-container-high': '#e8e8ea',
          'surface-container-highest': '#e2e2e5',
          'surface-container-lowest': '#ffffff',
          'surface-variant': '#e2e2e5',
          'surface-tint': '#745b00',
          'on-surface': '#1a1c1e',
          'on-surface-variant': '#4e4632',
          'inverse-surface': '#2f3133',
          'inverse-on-surface': '#f0f0f3',
          background: '#f9f9fc',
          'on-background': '#1a1c1e',
          error: '#ba1a1a',
          'error-container': '#ffdad6',
          'on-error': '#ffffff',
          'on-error-container': '#93000a',
          outline: '#80765f',
          'outline-variant': '#d2c5ab',
        },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body: ['Work Sans', 'sans-serif'],
        label: ['Work Sans', 'sans-serif'],
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};
